SOURCES += add_vector_coord.c
SOURCES += add_vector_vector.c
SOURCES += color_to_int.c
SOURCES += create_color.c
SOURCES += create_icolor.c
SOURCES += create_interval.c
SOURCES += create_point3.c
SOURCES += create_vector.c
SOURCES += distance2.c
SOURCES += distance3.c
SOURCES += distance_point3.c
SOURCES += distance_square2.c
SOURCES += distance_square3.c
SOURCES += distance_square_point3.c
SOURCES += div_vector_coord.c
SOURCES += div_vector_value.c
SOURCES += div_vector_vector.c
SOURCES += ft_abs.c
SOURCES += ft_append_strs.c
SOURCES += ft_atoi.c
SOURCES += ft_bzero.c
SOURCES += ft_calloc.c
SOURCES += ft_close_file.c
SOURCES += ft_contains_char.c
SOURCES += ft_count_file_lines.c
SOURCES += ft_create_file_content.c
SOURCES += ft_ctostr.c
SOURCES += ft_destroy_file_content.c
SOURCES += ft_destroy_splitted.c
SOURCES += ft_fabs.c
SOURCES += ft_fill_file_content.c
SOURCES += ft_find_char.c
SOURCES += ft_fmax.c
SOURCES += ft_fmin.c
SOURCES += ft_get_file_content.c
SOURCES += ft_get_splitted_size.c
SOURCES += ft_iabsui.c
SOURCES += ft_ll_length.c
SOURCES += ft_lltoa_ibase.c
SOURCES += ft_lowercase_char.c
SOURCES += ft_map.c
SOURCES += ft_max.c
SOURCES += ft_memset.c
SOURCES += ft_min.c
SOURCES += ft_natoi.c
SOURCES += ft_open_file.c
SOURCES += ft_printf.c
SOURCES += ft_putchar.c
SOURCES += ft_putchar_err.c
SOURCES += ft_putchar_errnl.c
SOURCES += ft_putchar_fd.c
SOURCES += ft_putchar_fdnl.c
SOURCES += ft_putchar_nl.c
SOURCES += ft_puti.c
SOURCES += ft_puti_err.c
SOURCES += ft_puti_errnl.c
SOURCES += ft_puti_fd.c
SOURCES += ft_puti_fdnl.c
SOURCES += ft_puti_nl.c
SOURCES += ft_putl.c
SOURCES += ft_putl_err.c
SOURCES += ft_putl_errnl.c
SOURCES += ft_putl_fd.c
SOURCES += ft_putl_fdnl.c
SOURCES += ft_putl_nl.c
SOURCES += ft_putll.c
SOURCES += ft_putll_err.c
SOURCES += ft_putll_errnl.c
SOURCES += ft_putll_fd.c
SOURCES += ft_putll_fdnl.c
SOURCES += ft_putll_nl.c
SOURCES += ft_putnchar.c
SOURCES += ft_putnchar_err.c
SOURCES += ft_putnchar_errnl.c
SOURCES += ft_putnchar_fd.c
SOURCES += ft_putnchar_fdnl.c
SOURCES += ft_putnchar_nl.c
SOURCES += ft_putstr.c
SOURCES += ft_putstr_err.c
SOURCES += ft_putstr_errnl.c
SOURCES += ft_putstr_fd.c
SOURCES += ft_putstr_fdnl.c
SOURCES += ft_putstr_nl.c
SOURCES += ft_putui.c
SOURCES += ft_putui_err.c
SOURCES += ft_putui_errnl.c
SOURCES += ft_putui_fd.c
SOURCES += ft_putui_fdnl.c
SOURCES += ft_putui_nl.c
SOURCES += ft_putul.c
SOURCES += ft_putul_err.c
SOURCES += ft_putul_errnl.c
SOURCES += ft_putul_fd.c
SOURCES += ft_putul_fdnl.c
SOURCES += ft_putul_nl.c
SOURCES += ft_putull.c
SOURCES += ft_putull_err.c
SOURCES += ft_putull_errnl.c
SOURCES += ft_putull_fd.c
SOURCES += ft_putull_fdnl.c
SOURCES += ft_putull_nl.c
SOURCES += ft_read_next_line.c
SOURCES += ft_split.c
SOURCES += ft_str_endwith.c
SOURCES += ft_strcmp.c
SOURCES += ft_strcpy.c
SOURCES += ft_strdup.c
SOURCES += ft_strlen.c
SOURCES += ft_strmult_back.c
SOURCES += ft_strmult_front.c
SOURCES += ft_strndup.c
SOURCES += ft_tolower.c
SOURCES += ft_toupper.c
SOURCES += ft_ull_ibase_length.c
SOURCES += ft_ull_length.c
SOURCES += ft_ulltoa_ibase.c
SOURCES += ft_uppercase_char.c
SOURCES += is_alpha.c
SOURCES += is_alphanumeric.c
SOURCES += is_ascii.c
SOURCES += is_lowercase.c
SOURCES += is_numeric.c
SOURCES += is_printable.c
SOURCES += is_space.c
SOURCES += is_uppercase.c
SOURCES += is_whitespace.c
SOURCES += mult_vector_coord.c
SOURCES += mult_vector_value.c
SOURCES += mult_vector_vector.c
SOURCES += normalize_vector.c
SOURCES += printf_c_processor.c
SOURCES += printf_create_printable.c
SOURCES += printf_display.c
SOURCES += printf_diuxx_processor.c
SOURCES += printf_dot_parser.c
SOURCES += printf_is_valid_flag.c
SOURCES += printf_is_valid_type.c
SOURCES += printf_minus_parser.c
SOURCES += printf_p_processor.c
SOURCES += printf_parse_printable.c
SOURCES += printf_pcrt_processor.c
SOURCES += printf_preprocess.c
SOURCES += printf_process.c
SOURCES += printf_s_processor.c
SOURCES += printf_star_parser.c
SOURCES += printf_zero_parser.c
SOURCES += rotate_vector.c
SOURCES += rotate_vector_x.c
SOURCES += rotate_vector_y.c
SOURCES += rotate_vector_z.c
SOURCES += sub_vector_coord.c
SOURCES += sub_vector_vector.c
INCLUDES += libft.h
INCLUDES += libft_boolean.h
INCLUDES += libft_checker.h
INCLUDES += libft_color.h
INCLUDES += libft_converter.h
INCLUDES += libft_display.h
INCLUDES += libft_display_char.h
INCLUDES += libft_display_nbr.h
INCLUDES += libft_display_nbr_int.h
INCLUDES += libft_display_nbr_long.h
INCLUDES += libft_display_nbr_longlong.h
INCLUDES += libft_display_nbr_uint.h
INCLUDES += libft_display_nbr_ulong.h
INCLUDES += libft_display_nbr_ulonglong.h
INCLUDES += libft_display_str.h
INCLUDES += libft_file.h
INCLUDES += libft_math.h
INCLUDES += libft_math_point.h
INCLUDES += libft_math_pythagore.h
INCLUDES += libft_math_vector.h
INCLUDES += libft_memory.h
INCLUDES += libft_number.h
INCLUDES += libft_printf.h
INCLUDES += libft_printf_checker.h
INCLUDES += libft_printf_parser.h
INCLUDES += libft_printf_printable.h
INCLUDES += libft_printf_processor.h
INCLUDES += libft_strings.h

NAME			=	libft.a

BLACK			=	\033[0;30m
RED				=	\033[0;31m
GREEN			=	\033[0;32m
ORANGE			=	\033[0;33m
BLUE			=	\033[0;34m
PURPLE			=	\033[0;35m
CYAN			=	\033[0;36m
LIGHT_GRAY		=	\033[0;37m
DARK_GRAY		=	\033[1;30m
LIGHT_RED		=	\033[1;31m
LIGHT_GREEN		=	\033[1;32m
YELLOW			=	\033[1;33m
LIGHT_BLUE		=	\033[1;34m
LIGHT_PURPLE	=	\033[1;35m
LIGHT_CYAN		=	\033[1;36m
WHITE			=	\033[1;37m
NO_COLOR		=	\033[0m

INCLUDES_PATH	=	./
OBJS			=	$(SOURCES:.c=.o)

GCC				=	gcc
FLAGS			=	-Wall -Wextra -Werror -O3 -Ofast -flto -march=native -ffast-math
RM				=	rm -f

all: $(NAME)

%.o:	%.c $(INCLUDES)
	@$(GCC) $(FLAGS) -I $(INCLUDES_PATH) -c $< -o $@
	@printf "\033[2K\r$(BLUE)$(NAME): $(PURPLE)$<$(RESET)"

$(NAME): $(OBJS)
	@ar rc $(NAME) $(OBJS)
	@printf "\033[2K\r$(BLUE)$(NAME): $(GREEN)Compiled [√]$(RESET)\n"

clean:
	@$(RM) $(OBJS)
	@printf "$(BLUE)$(NAME): $(LIGHT_RED)Cleaning all .o in libft.\n$(RESET)"

fclean: clean
	@$(RM) $(NAME)
	@printf "$(BLUE)$(NAME): $(RED)Cleaning compiled library $(NAME).\n$(RESET)"

re: fclean all

gmk:
	@printf "$(BLUE)$(NAME): $(GREEN)Generating Makefile includes.\n$(RESET)"
	@find sources -name '*.c' | sed 's/^/SOURCES += /' > sources.mk
	@find includes -name '*.h' | sed 's/^/INCLUDES += /' > includes.mk

norminette: clean
	@printf "$(BLUE)$(NAME): $(GREEN)norminette -> sources\n$(RESET)"
	@norminette sources
	@echo " "
	@printf "$(BLUE)$(NAME): $(GREEN)norminette -> includes\n$(RESET)"
	@norminette includes

norminette-exported: clean
	@printf "$(BLUE)$(NAME): $(GREEN)norminette exported\n$(RESET)"
	@norminette

export:
	@./scripts/export.sh
	@printf "$(BLUE)$(NAME): $(YELLOW)Libft exported.\n$(RESET)"

end:
	@make fclean
	@make gmk
	@make all
	@make norminette
	@make fclean
	@make export
	@printf "$(BLUE)$(NAME): $(LIGHT_CYAN)Prepared to be pushed.\n$(RESET)"

.PHONY: all clean fclean re gmk norminette norminette-exported export end
